from sqlalchemy import *
from config import host, port, database, user, password

conn_str = f"postgresql://{user}:{password}@{host}/{database}"
engine = create_engine(conn_str)
connection = engine.connect()
metadata = MetaData()
user_tb = Table('bpv_users', metadata,
   Column('user_id', Integer, primary_key = True),
   Column('user_education', String(255)),
   Column('pre_quiz_q1', String(255)),
   Column('pre_quiz_q2', String(255)),
   Column('pre_quiz_q3', String(255)),
   Column('pre_quiz_q4', String(255)),
   Column('pre_quiz_q5', String(255)),
   Column('post_quiz_q1', String(255)),
   Column('post_quiz_q2', String(255)),
   Column('post_quiz_q3', String(255)),
   Column('post_quiz_q4', String(255)),
   Column('post_quiz_q5', String(255)),
   Column('survey_q1', String(255)),
   Column('survey_q2', String(255)),
   Column('survey_q3a', String(255)),
   Column('survey_q3b', String(255)),
   Column('survey_q4a', String(255)),
   Column('survey_q4b', String(255)),
   Column('survey_q5a', String(255)),
   Column('survey_q5b', String(255)),
   Column('survey_q6', String(255)),
   Column('survey_q7a', String(255)),
   Column('survey_q7b', String(255)),
   Column('survey_q8', String(255)),
   Column('bp_measuring_practices_status', String(255)),
   Column('treatment_adherence_status', String(255)),
   Column('lifestyle_status', String(255)),
   Column('medication_hist_status', String(255)),
   Column('patient_obs_status', String(255)),
   Column('patient_hist_status', String(255)),
   Column('other_factors_status', String(255)),
   Column('bp_measuring_practices_status_1', String(255)),
   Column('bp_measuring_practices_status_2', String(255)),
   Column('bp_measuring_practices_status_1a', String(255)),
   Column('bp_measuring_practices_status_1b', String(255)),
   Column('bp_measuring_practices_status_1c', String(255)),
   Column('bp_measuring_practices_status_1d', String(255)),
   Column('bp_measuring_practices_status_2a', String(255)),
   Column('bp_measuring_practices_status_2b', String(255)),
   Column('bp_measuring_practices_status_2c', String(255)),
   Column('bp_measuring_practices_status_2d', String(255)),
   Column('bp_measuring_practices_status_2aa', String(255)),
   Column('bp_measuring_practices_status_2ab', String(255)),
   Column('bp_measuring_practices_status_2aaa', String(255)),
   Column('bp_measuring_practices_status_2aab', String(255)),
   Column('bp_measuring_practices_status_2aac', String(255)),
   Column('bp_measuring_practices_status_2ba', String(255)),
   Column('bp_measuring_practices_status_2bb', String(255)),
   Column('bp_measuring_practices_status_2bc', String(255)),
   Column('bp_measuring_practices_status_2da', String(255)),
   Column('bp_measuring_practices_status_2db', String(255)),
   Column('bp_measuring_practices_1aa_status', String(255)),
   Column('bp_measuring_practices_1ab_status', String(255)),
   Column('bp_measuring_practices_1ba_status', String(255)),
   Column('bp_measuring_practices_1bb_status', String(255)),
   Column('lifestyle_status_a', String(255)),
   Column('lifestyle_status_b', String(255)),
   Column('lifestyle_status_c', String(255)),
   Column('lifestyle_status_d', String(255)),
   Column('lifestyle_status_e', String(255)),
   Column('lifestyle_status_f', String(255)),
   Column('lifestyle_status_ca', String(255)),
   Column('lifestyle_status_cb', String(255)),
   Column('lifestyle_status_cc', String(255)),
   Column('lifestyle_status_da', String(255)),
   Column('lifestyle_status_db', String(255)),
   Column('treatment_adherence_status_a', String(255)),
   Column('treatment_adherence_status_b', String(255)),
   Column('medication_hist_status_a', String(255)),
   Column('medication_hist_status_b', String(255)),
   Column('medication_hist_status_c', String(255)),
   Column('medication_hist_status_d', String(255)),
   Column('medication_hist_status_e', String(255)),
   Column('medication_hist_status_f', String(255)),
   Column('medication_hist_status_g', String(255)),
   Column('medication_hist_status_h', String(255)),
   Column('other_factors_status_a', String(255)),
   Column('other_factors_status_b', String(255)),
   Column('other_factors_status_ba', String(255)),
   Column('other_factors_status_bb', String(255)),
   Column('patient_obs_status_a', String(255)),
   Column('patient_obs_status_b', String(255)),
   Column('patient_obs_status_c', String(255)),
   Column('patient_obs_status_d', String(255)),
   Column('patient_obs_status_1', String(255)),
   Column('patient_obs_status_2', String(255)),
   Column('patient_review_status_a', String(255)),
   Column('patient_review_status_b', String(255)),
   Column('patient_review_status_c', String(255)),
   Column('patient_review_status_d', String(255)),
   Column('patient_review_status_1', String(255)),
   Column('patient_review_status_2', String(255)),
)

metadata.create_all(engine)
